### ISSUE TITLE
Django CI/CD Test

### ISSUE THREAD

**Issue by separk314** [separk314/Django_lab#1]
### Description
- 장고 CI/CD 테스트

### To-do list
- [x] CI  
- [ ] CD
- [ ] secrets.json 파일 추가

**Comment by separk314** [comment]
- [X] 문제1) ec2에서 screts.json을 생성할 때 깃헙 secret 값을 가져오지 않음
- [ ] 문제2) 실행 중인 프로세스를 kill 하고 재배포 하는 방법 (err: Error: That port is already in use.)
